### ISSUE TITLE
`getCookieConsentValue` returns always undefined using custom cookie name

### ISSUE THREAD

**Issue by massimo-cassandro** [Mastermindzh/react-cookie-consent#191] opened 2023-10-02 16:07 UTC
Setting the `cookieName` prop to some value causes the `getCookieConsentValue` to always return `undefined`

**Comment by Mastermindzh** [comment] 2023-10-02 19:09
Hey,

Do you have a minimal reproduction?
I can't reproduce it locally. Did you specify the name for the `getCookieConsentValue` as well?

```jsx
<CookieConsent
  location="bottom"
  buttonText="Sure man!!"
  cookieName="myAwesomeCookieName2"
  style={{ background: "#2B373B" }}
  buttonStyle={{ color: "#4e503b", fontSize: "13px" }}
  expires={150}
>
    This website uses cookies to enhance the user experience.{" "}
    <span style={{ fontSize: "10px" }}>This bit of text is smaller :O</span>
</CookieConsent>
<p>current cookie version: {getCookieConsentValue("myAwesomeCookieName2")}</p>
```

**Comment by massimo-cassandro** [comment] 2023-10-03 09:02
You are right, I missed the `getCookieConsentValue` argument, but the documentation is not very clear on this.

I would also suggest grouping the props by topic (e.g., buttons, cookies, style, classes, etc.) to make them easier to navigate.

Thanks for your assistance, and congratulations for the great 'react-cookie-consent' component.

**Comment by cmahnke** [comment] 2023-10-15 18:23
Consider reopening issue, since I thought to have the same issue, until I found this report. I strongly advise to change this to a documentation issue and improve the description of `getCookieConsentValue` to include the requirement to pass a `cookieName`.

**Comment by Mastermindzh** [comment] 2023-10-16 08:37
@cmahnke I agree. I didn't close it after the initial answer because I was about to update documentation.

I wasn't home for the past week though so I hadn't gotten around to it :)

**Closed** 2023-10-16 21:43 UTC
Labels: Can't reproduce
